name: CD/CI
on:
  push:
    branches:
      - master
      - main
      - dev
  pull_request:
    branches:
      - master
      - main
      - dev
env:
  IMAGE_NAME: seriadiallo/fastapi-githubactions

jobs:
  Fastapi-project-ci:
    runs-on: ubuntu-latest
    steps:
      - name: "Cloning repository"
        uses: actions/checkout@v3

      - name: Login to docker
        run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASS }}
      - name: Build docker image
        run: docker build -t $IMAGE_NAME:${GITHUB_REF_NAME}  src
      - name: Push docker image
        run: docker push $IMAGE_NAME:${GITHUB_REF_NAME} 
      - name: "finish"
        run: echo " The job was successful."

